# Generated by Django 4.2.17 on 2025-01-16 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DSR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_file', models.FileField(upload_to='uploads/')),
                ('date_of_generation', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.CharField(max_length=500)),
                ('original_name', models.CharField(blank=True, max_length=255, null=True)),
                ('special_remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('total_qty_sold', models.FloatField(default=0.0)),
                ('total_amount_template', models.FloatField(default=0.0)),
                ('total_amount_raw', models.FloatField(default=0.0)),
                ('uploader', models.CharField(max_length=200)),
                ('extracted_data', models.JSONField(null=True)),
                ('instance', models.CharField(max_length=100)),
                ('chain', models.CharField(max_length=100)),
                ('database', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-date_of_generation'],
            },
        ),
    ]
