# Generated by Django 4.2.17 on 2025-01-16 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSR_APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsr',
            name='new_total',
            field=models.IntegerField(default=0),
        ),
    ]
