# Generated by Django 4.2.17 on 2025-01-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSR_APP', '0002_dsr_new_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsr',
            name='total_qty_sold',
            field=models.IntegerField(default=0),
        ),
    ]
