# Generated by Django 4.2.17 on 2025-02-20 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSR_APP', '0004_remove_dsr_new_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_file', models.FileField(upload_to='uploads/')),
                ('date_of_comparison', models.DateTimeField(auto_now_add=True)),
                ('original_name', models.CharField(blank=True, max_length=255, null=True)),
                ('data_from_generated_file', models.JSONField(null=True)),
            ],
            options={
                'ordering': ['-date_of_comparison'],
            },
        ),
    ]
