# Generated by Django 4.2.17 on 2025-02-20 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSR_APP', '0005_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='validation',
            name='instance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
