# Generated by Django 4.2.17 on 2025-02-20 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSR_APP', '0006_validation_instance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validation',
            name='generated_file',
            field=models.FileField(upload_to='validation/'),
        ),
    ]
